### ISSUE TITLE
Let agency dispatchers assign trip IDs

### ISSUE THREAD

**Issue by unreasonableman** [cal-itp/graas#103]
A proposal to free drivers from the grind of having to start and stop trips manually.

- [ ] On-device web app: add `patrol` mode so that app constantly sends location updates without trip ID, but with vehicle ID
- [ ] Desktop web client for dispatcher
  - [ ] auth through QR code or copy-pasted agency key
  - [ ] inactive list of buses that aren't assigned trips
  - [ ] active list of buses that are assigned trips
  - [ ] switching buses between lists
    - [ ] to activate, select inactive vehicle and choose `Assign Trip`, which brings up trip dropdown
    - [ ] to deactivate, select vehicle and choose `End Trip`
- [ ] Server
  - [ ] new endpoint `/assign-vehicle` expects JSON that has `agency-id`, `vehicle-id` and `trip-id`
    - [ ] create unique id: `<agency-id>-<vehicle-id>`
    - [ ] write id and trip id to `Assignment` DB table
    - [ ] trip-id can be `unassigned`
  - [ ] regular vehicle position update endpoint:
    - [ ] if update without trip-id comes in, create unique id: `<agency-id>-<vehicle-id>`. Get `trip-id` value from assignment table. If `unassigned` add to unassigned feed (see below), otherwise add `trip-id` field and proceed with normal update flow
- [ ] Map
  - [ ] to show unassigned buses on map, create new feed `/unassigned-vehicle-positions` which has the same structure as `/vehicle-positions`, except trip IDs are all `unassigned`

**Comment by owades** [comment]
Closing this out as I believe bulk assignment meets this need!
