### ISSUE TITLE
Assess how much work is needed to have TripListGenerator use Util.loadCollections()

### ISSUE THREAD

**Issue by unreasonableman** [cal-itp/graas#110]
TripListGenerator currently duplicates a fair amount of functionality provided by the gtfu *Collection classes and the Util.loadCollections() convenience method. TLG has some specialized needs regarding trip details that may not currently be present in the Trip class, but it would make sense to just add it. We want TLG to use a pattern like this:

```
        Map<String, Object> collections = Util.loadCollections(cacheFolder, agencyID, new ConsoleProgressObserver(40));
        ShapeCollection shapes = (ShapeCollection)collections.get("shapes");
        BlockCollection blocks = (BlockCollection)collections.get("blocks");
```

instead of manually loading  and parsing GTFS files.

**Comment by owades** [comment]
@unreasonableman fyi I'm taking some time today to test this out
