### ISSUE TITLE
route and vehicle dropdowns blank upon first start after QR scan

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#18]
Copied from GRaaS Staging, notes from @unreasonableman:

Scanned QR code for TCRTA on ipad, then pressed Start button. Dropdowns were empty. Checked filter params and route bucket files, both looked reasonable. Ran web app on desktop safari wit js console open to debug. Routes showed up. Went back to ipad, quit out of safari there and restarted. Issue did not persist past restart.

This may be harder to debug, but it's a bad first impression if it happens.

Additional detail: the dropdowns were completely blank, i.e. didn't have "Select Route" or "Select Vehicle". This suggests either a crash or a stall, and not a filtering issue.

**Comment by owades** [comment]
UI opens before data is loaded. May want to disable dropdowns until results have come in.

**Comment by unreasonableman** [comment]
And show a status that says "loading data" or something so that there's not
disabled widgets with no explanation.
