### ISSUE TITLE
duplicate variable MILLIS_PER_MINUTE

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#235]
After deploying to staging, I got the following error upon loading the page:
`SyntaxError: Can't create duplicate variable: 'MILLIS_PER_MINUTE'`

The const is defined both graas.js and gtfs-rt-util.js

**Comment by owades** [comment]
fyi @unreasonableman  - no deploy tonight

**Comment by unreasonableman** [comment]
Looks like js linting got a major priority boost.
