### ISSUE TITLE
Weekday routes appearing on Saturday GRaaS report

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#61]
Both the driver + iPad and TripInference appear to have selected a weekday route during Saturday service.

All four trips in the screenshotted saturday GRaaS report are weekday trips, according to both Glenn's static gtfs and route-names.json.

![report-1 (18)](https://user-images.githubusercontent.com/3301353/150896116-0e95e49f-ea78-4f7f-94d8-c59bab39bf9c.png)

**Comment by unreasonableman** [comment]
This appears to be a one-off incident, closing.
