### ISSUE TITLE
Auto-update route-names.json based on static GTFS

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#84]
Prevent route-names.json from getting out-of-sync with static-gtfs files. This also streamlines agency onboarding.

1. Add TripListGenerator flags (headsign vs route name, direction) to filter-params.json. Rename it to something more generic, such as "agency-params".
2. Update TripListGenerator to check the gcloud bucket for agency-params.json, and use the flags listed in that file to run TripListGenerator. We'll need to update GCloudStorage.java to include a function for getting an object from the bucket.
3. Update TripListGenerator to save results directly to route-names.json in the gcloud bucket. Rename to trip-names.json while we're at it.
4. Create a daily job on GH actions that checks when route-names.json was last updated, and when the static feed was last updated. If the feed was updated after, re-generate trip-names.json. Include some form of alerting that tells us what was updated.

**Comment by unreasonableman** [comment]
@owades that looks good. "alerting that tells us what was updated", could a a diff between old and new version. Dramatic changes should be cause for review
