### ISSUE TITLE
Wake lock not working on iPhone

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#91]

**Comment by unreasonableman** [comment]
On my iphone XR with iOS 15.1 with web app version 0.15, the wake lock no longer prevents the device from going to sleep when a trip is running. The screen darkens when the auto-lock time in the display settings is reached, and updates to the server stop.

**Comment by unreasonableman** [comment]
When investigating this issue, be aware that many phones have a feature where they don't lock as long as a face is looking directly at the screen. Locking also usually doesn't happen when the phone is connected to USB and/or power.

**Comment by unreasonableman** [comment]
Just confirmed that wake lock works as expected for the ipad

**Comment by unreasonableman** [comment]
After some debugging it seems like nosleep.js wake lock is set, but doesn't actually work. (This)[https://github.com/richtr/NoSleep.js/issues/135] GH issue seems to confirm. It mentions a workaround, which I will look into.

**Comment by unreasonableman** [comment]
Confirmed that issue is resolved by workaround when running server locally and publishing with `ngrok`. Checked on iphone XR, ipad and Moto G, also checked that device will go to sleep again after calling `nosleep.disable()`.

**Comment by unreasonableman** [comment]
Fixed with PR #96
